version: '3.8'

services:
  # Banco Relacional (SQL) - Para Tarefas, Usu√°rios e Eventos
  postgres:
    image: postgres:15
    container_name: todolist_postgres
    environment:
      POSTGRES_DB: todolist_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Banco NoSQL (Documentos) - Para Subtarefas
  mongo:
    image: mongo:6.0
    container_name: todolist_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # Cache - Para performance de leitura
  redis:
    image: redis:7.0
    container_name: todolist_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  mongo_data:
  redis_data:
