version: '3.8'

services:
  # Banco de Dados Relacional (SQL)
  postgres:
    image: postgres:15-alpine
    container_name: todolist_postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: todolist_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - todolist-network
  mongo:
    image: mongo:6.0
    container_name: todolist_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - todolist-network

  # Cache em Mem√≥ria
  redis:
    image: redis:7-alpine
    container_name: todolist_redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - todolist-network

volumes:
  postgres_data:
  mongo_data:
  redis_data:


networks:
  todolist-network:
    driver: bridge
